### PR TITLE
Larger file storage

### LINKED ISSUE #26: mongodb file size limitations
I just came across a `pymongo.errors.DocumentTooLarge` error on a very small dataset, probably because I accidentally produced a huge transition matrix. We might need to solve this problem sooner or later, especially because the discrete trajectories become larger and larger with time...

### PR DESCRIPTION
**Pull request by jhprinz**
resolves #26.

Add the possibility to store arbitrary large objects. So far this is only used by PyEMMAModel to save the returned results. This is handled by gridFS and it automatically divides large files into blocks.

I also store the result model.json in a folder in `projects/proj-name/models` for later processing.

### CODE REVIEW

**Comment by jhprinz** [comment]
Done.

**Comment by jhprinz** [comment]
If @thempel has more problems with file sizes we can use the same for storing file contents in general...

**Comment by thempel** [comment]
In general: Yes, it would be good to not be limited in the system size. The system I am working with right now is not very big (25,000 atoms) and the files that need to be moved around are about 11.5 MB, so already pretty close to the 16 MB. In the case mentioned in #28, I suspect another problem since it used to work before.

**Comment by jhprinz** [comment]
Done. This is implemented. This means (when it works) we have now all major features we talked about. The featurizer stuff would be icing on the cake. Who would have thought. I approach the pure 6000 lines of code... (not considering all that I added and deleted) :)

**Comment by jhprinz** [comment]
merging

**Pull request merged**
