### PR TITLE
[WIP] Implement trajectories as folders

### PR DESCRIPTION
**Pull request by jhprinz**
Almost done. Explanation will come tomorrow...

- [x] much simpler creation of tasks
- [x] better parsing of tasks into scripts
- [x] `Trajectories` are now folders
- [x] fix run traj
- [x] fix extend
- [x] fix RPC
- [x] update examples

This also contains all of the other changes as well. We will then have full flexibility in the output files of a simulation

### CODE REVIEW

**Comment by jhprinz** [comment]
Well, this is done.

Trajectories are by default folders now. I have also simplified a lot of the API, so have a look at example notebooks 4 and 5 to see how this works.

This does not add capabilities to work with reduced trajectories, but makes this easy to add.

What is tricky with trajectories is to access a file in the traj folder. You can use
```
traj.file('myfile')
```

to get the location of this file, so instead of moving with
```
bash = 'mv %s %s' % (traj_file, target_file)
# new
bash = 'mv %s %s' % (traj.file('output.dcd')', target.file('traj.dcd'))
```

**Comment by jhprinz** [comment]
I checked all examples and it should work better. There are also some little bugfixes for the RPC calls.

**Comment by jhprinz** [comment]
If there are no objections I would merge this.

**Comment by franknoe** [comment]
Thanks, that looks good to me. Please go ahead.

**Pull request merged**
